### ISSUE TITLE
When will you release the code?

### ISSUE THREAD

**Issue by topDreamer** [maarten-deraedt/IDAS-intent-discovery-with-abstract-summarization#1]
I'm very interested in your work and would really like to read the source code to understand the details better.
So I want to ask when will you release the code? Thanks!

**Comment by maarten-deraedt** [comment]
I am currently occupied with other things -- but I will make sure to release the code by next week Friday (September 8th). In case you need the code earlier, you can send me an email at maarten.deraedt@ugent.be.

**Comment by topDreamer** [comment]
Thank you for your prompt response, Maarten. I completely understand your current commitments. I'll patiently wait for the code release by next Friday. Once again, thank you for your cooperation and support! Wishing you all the best in your endeavors!
